apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-redis
  labels:
    app: {{ .Release.Name }}-redis
spec:
  containers:
    - name: {{ .Values.back.image }}-pod
      image: {{ .Values.back.image }}:{{ .Values.back.tag }}