apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.front.image }} 
  labels:
    app: {{ .Release.Name }}-{{ .Values.front.image }}
spec:
  replicas: {{ .Values.front.replica }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Values.front.image }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Values.front.image }}
    spec:
      restartPolicy: Always
      containers:
        - name: {{ .Values.front.image }} 
          image: {{ .Values.front.repo }}/{{ .Values.front.image }}:{{ .Values.front.tag }}
          ports:
            - containerPort: 7000
              protocol: TCP
        - name: {{ .Values.back.image }}-pod
          image: {{ .Values.back.image }}:{{ .Values.back.tag }}